type: static
description: |
  Example question to showcase the **static challenge** type with _markdown support_. 

  ## Background
  The Mobile Security Dojo is built on a specific mobile OS.
question: |
  Which **mobile operating system** is the Mobile Security Dojo based on?
  
  _Hint: It's the most popular mobile OS globally.
answer: "Android"